#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user

while IFS=':' read -r username _ userid _ homedir _
do
	echo "Username: $username"
	echo "User id: $userid"
	echo "Home directory: $homedir"
	echo
done < /etc/passwd
