#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL.
#USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

while IFS=':' read -r username _ userid _ GID _ homedir _ shell
do
	echo "Part of the GROUP_ID gang: $username"
	echo "User id: $userid"
	echo "Lives in: $homedir"
	echo "Rides: $shell"
	echo "The user $username is part of the $GID gang, lives in $homedir, and rides $shell"
        echo "$userid/'s place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < /etc/passwd
