#!/usr/bin/env bash
#Using what you did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
#Requirements:
#The exact format must be:
#OCCURENCE_NUMBER IP HTTP_CODE
#In list format
#Ordered from the greatest to the lowest number of occurrences

awk '{ count[$1,$9]++ } END { for (key in count) { split (key, arr, SUBSEP); print arr[1]; arr[2]; count[key] } }' apache-access.log
