#!/usr/bin/env bash
# write a script using an "until" loop that displays "Best School" 10 times.


iteration=0
until [ $iteration -ge 10 ]; do
  echo "Best School"
  iteration=$((iteration + 1))
done
