#!/usr/bin/env bash
# write a script using an "until" loop that displays "Best School" 10 times.


iteration=1
while [ $iteration -le 11 ]; do
  if [ $iteration -eq 10 ]; then
	  echo "Hi"
  else
	  echo "Best School"
  fi
  iteration=$((iteration + 1))
done
