#!/usr/bin/env bash
#Write a Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


	function handle_sigterm()
{
	echo "I hate the kill command";
}
	function handle_sigtint()
{
	echo "Y U no love me?!";
}
	function handle_sigquit()
{
	echo "Deleting PID file and terminating script";
	rm -f /var/run/myscript.pid
	exit
}

	trap handle_sigterm SIGTERM
	trap handle_sigint SIGINT
	trap handle_sigquit SIGQUIT SIGTERM

	echo $$ > /var/run/myscript.pid

	while true; do
	echo "To infinity and beyond"
	sleep 1
done
