#!/usr/bin/env bash
#Write a manage_my_process Bash script that:
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
#Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)
#Requirements:
#When passing the argument start:
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started
#When passing the argument stop:
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped
#When passing the argument restart
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed



/etc/init.d/manage_my_process start
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"

/etc/init.d/manage_my_process stop
rm -f /var/run/my_process.pid
echo "manage_my_process stopped"

/etc/init.d/manage_my_process restart
rm -f /var/run/my_process.pid
/etc/init.d/manage_my_process start
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
echo "Usage: manage_my_process {start|stop|restart}"




