#!/usr/bin/env bash
#Write a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

./3-show_your_bash_pid_made_easy:pstree -p | awk '/bash/ {gsub(/[^0-9]/,"",$1); print $1}' | grep --color green ./*
