#!/usr/bin/env bash
#Write a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
grep -rIl "bash" /proc/*/comm 2>/dev/null | xargs -I {} sh -c "echo "PID: $(basename "$(dirname "{}")"), Process Name: "$(cat "{}")""
