#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process.

pid=$(pidof 4-to_infinity_and_beyond)

if [ -z "$pid" ]; then
	echo "Process id $pid not activated"
else 
	kill "$pid"
	echo "Process id $pid terminated"
fi
