#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process.

pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

if [ -z "$pid ]; then
	echo "Process not running"
else
	kill "$pid"
	echo "Process has been stopped"
fi
