#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process.

pid=$(pidof -sx 4-to_infinity_and_beyond)

if [ -z "$pid ]; then
	echo "Process not running"
else
	kill "$pid"
	echo "Process has been stopped"
fi
